logging:
  level: INFO
  loggers:
    com.chikitania: DEBUG

serverName: CHIKITANIA API SERVER

server:
  rootPath: /api/

  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091

database:
  # Postgres Database
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password:

  # the JDBC URL
  url: jdbc:mysql://localhost:3306/chikitania

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.show_sql: true
    hibernate.dialect: org.hibernate.dialect.MySQLDialect  #org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.connection.CharSet: utf8
    hibernate.connection.characterEncoding: utf8
    hibernate.connection.useUnicode: true
    hibernate.hbm2ddl.auto: update
    #hibernate.hbm2ddl.import_files: /db_scripts/mysql_script.sql

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

externalServers:

uploadDirectory: C:/uploads/

installerCommission: 4
